### PR TITLE
Added player number argument to get_hole_card()

### PR DESCRIPTION
**Pull request by paul-chelarescu**
This change should bring the codebase in sync with the updated version of https://github.com/JakubPetriska/acpc-python-client

### CODE REVIEW

**Comment by JakubPetriska** [comment]
Hi @paul-chelarescu , thanks for the PR! However I will probably not accept it. There is a `dev` branch which contains new version of this collection of algorithms and the change in `acpc-python-client` is already reflected in there. See https://github.com/JakubPetriska/poker-agent-kit/tree/dev . I will try to update the documentation and merge that into master ASAP.

**Comment by paul-chelarescu** [comment]
Alright, in that case you can close this PR and I'll pull the changes from dev, your repository is excellent nonetheless :)

**Comment by JakubPetriska** [comment]
Thanks. I'll try to update the docs and merge this soon.

**Comment by JakubPetriska** [comment]
@paul-chelarescu Hi, just an FYI, I merged the `dev` branch with all algorithms into `master` and added very brief README. Feel free to browse the repo if you're still interested in this.

**Pull request closed without merging**
